name    'puppet-module-auditusers'
version '1.0.1'
source 'Linkoping HUB'
author 'Mattias Winther'
license 'Apache License, Version 2.0'
summary 'A module to handle auditing of users via the biit360 system'
